apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: www-app
  name: www-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: www-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: www-app
    spec:
      containers:
      - image: 398266723651.dkr.ecr.eu-west-1.amazonaws.com/myrepo
        name: www-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: www-app-service
spec:
  selector:
    run: www-app
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: www-app-service
              servicePort: 80