AWSTemplateFormatVersion: '2010-09-09'
Description: 'EIP Template'


Resources:

    EIP:
        Type: AWS::EC2::EIP
        Properties:
          Domain: vpc


Outputs:
    ElasticIP:
        Value: !Ref EIP